import sqlite3
from tkinter import* #tkinter module
from tkinter import messagebox
import time 
import random
import nltk
from nltk.corpus import words
#nltk.download('words')
word_list = words.words()
word=['beautiful','diet','trojan','mouse','java','yuuca','libray','laid','technology','bad','demo','cabin',]
l_list=['A','B','C','D','E','F','H','K','T','N','S','J','L','I','M','O','R','U','W']
conn=sqlite3.connect('scarmble.db')
c=conn.cursor()
#c.execute("drop table scramble")
#c.execute("create table scramble(temp1 number)")
w=Tk()
w.geometry("1000x750")
f1=Frame(w,borderwidth=2)
f1.grid(row=0,column=0)
logo=PhotoImage(file="title.png")
l=Label(f1,image=logo)
l.grid(row=0,column=1)
f2=Frame(w,borderwidth=4)
f2.grid(row=1,column=0)
f3=Frame(w,borderwidth=2)
f3.grid(row=0,column=1)
label=Label(f3,text="Score = 0",bg="green", fg="Black",font=('Helvetica','20'))
label.grid(row=1,column=5)
hscore=Label(f3,text="Highest Score = 0",bg="pink", fg="Black",font=('Helvetica','20'))
hscore.grid(row=1,column=6)
f4=Frame(w,borderwidth=2)
f4.grid(row=1,column=1)
label1=Label(f4,text="Words Found",bg="brown4", fg="Black",font=('Helvetica','15'))
label1.grid(row=2,column=1)
label2=Label(f4,text="Letters Selected= ",bg="cyan2", fg="Black",font=('Helvetica','20'))
label2.grid(row=0,column=1)
reset = Button(f4, text="Reset Letters",bg="dark orchid4", fg="white",font=('Helvetica','10'),command=lambda:reset1(reset))
reset.grid(column=1, row=1)
reset2 = Button(f2, text="Reset Game",bg="black", fg="yellow",font=('Helvetica','10'),command=lambda:click1(reset2))
reset2.grid(row=13, column=14)
found=0
count=0
total=""
strg=""
score=0
strng=0
l=list()
w_found='words found'
l_found=""
def reset1(reset):
    global strg
    found=0
    strg=""
    l_found=strg
    label2.configure(text="letters selected= "+l_found)
def click1(reset2):
    global total
    global found
    global strg
    global count
    global l
    global score
    global w_found
    global l_found
    found=0
    count=0
    strg=""
    score=0
    strng=0
    l=[]
    total=""
    w_found='Words Found'
    l_found=""
    label1.configure(text=w_found)
    label.configure(text="Score= 0")
    label2.configure(text="Letters Selected= "+l_found)
    btn11 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn11))
    btn11.grid(column=1, row=1)
    btn12 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn12))
    btn12.grid(column=2, row=1)
    btn13 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn13))
    btn13.grid(column=3, row=1)
    btn14 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn14))
    btn14.grid(column=4, row=1)
    btn15 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn15))
    btn15.grid(column=5, row=1)
    btn16 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn16))
    btn16.grid(column=6, row=1)
    btn17 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn17))
    btn17.grid(column=7, row=1)
    btn18 = Button(f2, text="L",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn18))
    btn18.grid(column=8, row=1)
    btn19 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn19))
    btn19.grid(column=9, row=1)
    btn110 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn110))
    btn110.grid(column=10, row=1)
    btn111a = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn111a))
    btn111a.grid(column=11, row=1)
    btn11298 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn11298))
    btn11298.grid(column=12, row=1)

    btn21 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn21))
    btn21.grid(column=1, row=2)
    btn22 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn22))
    btn22.grid(column=2, row=2)
    btn23 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn23))
    btn23.grid(column=3, row=2)
    btn24 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn24))
    btn24.grid(column=4, row=2)
    btn25 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn25))
    btn25.grid(column=5, row=2)
    btn26 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn26))
    btn26.grid(column=6, row=2)
    btn27 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn27))
    btn27.grid(column=7, row=2)
    btn28 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn28))
    btn28.grid(column=8, row=2)
    btn29 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn29))
    btn29.grid(column=9, row=2)
    btn210 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn210))
    btn210.grid(column=10, row=2)
    btn211 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn211))
    btn211.grid(column=11, row=2)
    btn212 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn212))
    btn212.grid(column=12, row=2)

    btn31 = Button(f2, text="M",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn31))
    btn31.grid(column=1, row=3)
    btn32 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn32))
    btn32.grid(column=2, row=3)
    btn33 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn33))
    btn33.grid(column=3, row=3)
    btn34 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn34))
    btn34.grid(column=4, row=3)
    btn35 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn35))
    btn35.grid(column=5, row=3)
    btn36 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn36))
    btn36.grid(column=6, row=3)
    btn37 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn37))
    btn37.grid(column=7, row=3)
    btn38 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn38))
    btn38.grid(column=8, row=3)
    btn39 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn39))
    btn39.grid(column=9, row=3)
    btn310 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn310))
    btn310.grid(column=10, row=3)
    btn311 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn311))
    btn311.grid(column=11, row=3)
    btn312 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn312))
    btn312.grid(column=12, row=3)

    btn41 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn41))
    btn41.grid(column=1, row=4)
    btn42 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn42))
    btn42.grid(column=2, row=4)
    btn43 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn43))
    btn43.grid(column=3, row=4)
    btn44 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn44))
    btn44.grid(column=4, row=4)
    btn45 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn45))
    btn45.grid(column=5, row=4)
    btn46 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn46))
    btn46.grid(column=6, row=4)
    btn47 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn47))
    btn47.grid(column=7, row=4)
    btn48 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn48))
    btn48.grid(column=8, row=4)
    btn49 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn49))
    btn49.grid(column=9, row=4)
    btn410 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn410))
    btn410.grid(column=10, row=4)
    btn411 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn411))
    btn411.grid(column=11, row=4)
    btn412 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn412))
    btn412.grid(column=12, row=4)

    btn51 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn51))
    btn51.grid(column=1, row=5)
    btn52 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn52))
    btn52.grid(column=2, row=5)
    btn53 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn53))
    btn53.grid(column=3, row=5)
    btn54 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn54))
    btn54.grid(column=4, row=5)
    btn55 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn55))
    btn55.grid(column=5, row=5)
    btn56 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn56))
    btn56.grid(column=6, row=5)
    btn57 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn57))
    btn57.grid(column=7, row=5)
    btn58 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn58))
    btn58.grid(column=8, row=5)
    btn59 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn59))
    btn59.grid(column=9, row=5)
    btn510 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn510))
    btn510.grid(column=10, row=5)
    btn511 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn511))
    btn511.grid(column=11, row=5)
    btn512 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn512))
    btn512.grid(column=12, row=5)

    btn61 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn61))
    btn61.grid(column=1, row=6)
    btn62 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn62))
    btn62.grid(column=2, row=6)
    btn63 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn63))
    btn63.grid(column=3, row=6)
    btn64 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn64))
    btn64.grid(column=4, row=6)
    btn65 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn65))
    btn65.grid(column=5, row=6)
    btn66 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn66))
    btn66.grid(column=6, row=6)
    btn67 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn67))
    btn67.grid(column=7, row=6)
    btn68 = Button(f2, text="j",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn68))
    btn68.grid(column=8, row=6)
    btn69 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn69))
    btn69.grid(column=9, row=6)
    btn610 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn610))
    btn610.grid(column=10, row=6)
    btn611 = Button(f2, text="U",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn611))
    btn611.grid(column=11, row=6)
    btn612 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn612))
    btn612.grid(column=12, row=6)

    btn71 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn71))
    btn71.grid(column=1, row=7)
    btn72 = Button(f2, text="F",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn72))
    btn72.grid(column=2, row=7)
    btn73 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn73))
    btn73.grid(column=3, row=7)
    btn74 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn74))
    btn74.grid(column=4, row=7)
    btn75 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn75))
    btn75.grid(column=5, row=7)
    btn76 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn76))
    btn76.grid(column=6, row=7)
    btn77 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn77))
    btn77.grid(column=7, row=7)
    btn78 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn78))
    btn78.grid(column=8, row=7)
    btn79 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn79))
    btn79.grid(column=9, row=7)
    btn710 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn710))
    btn710.grid(column=10, row=7)
    btn711 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn711))
    btn711.grid(column=11, row=7)
    btn712 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn712))
    btn712.grid(column=12, row=7)

    btn81 = Button(f2,text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn81))
    btn81.grid(column=1, row=8)
    btn82 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn82))
    btn82.grid(column=2, row=8)
    btn83 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn83))
    btn83.grid(column=3, row=8)
    btn84 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn84))
    btn84.grid(column=4, row=8)
    btn85 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn85))
    btn85.grid(column=5, row=8)
    btn86 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn86))
    btn86.grid(column=6, row=8)
    btn87 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn87))
    btn87.grid(column=7, row=8)
    btn88 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn88))
    btn88.grid(column=8, row=8)
    btn89 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn89))
    btn89.grid(column=9, row=8)
    btn810 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn810))
    btn810.grid(column=10, row=8)
    btn811 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn811))
    btn811.grid(column=11, row=8)
    btn812 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn812))
    btn812.grid(column=12, row=8)

    btn91 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn91))
    btn91.grid(column=1, row=9)
    btn92 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn92))
    btn92.grid(column=2, row=9)
    btn93 = Button(f2, text="I",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn93))
    btn93.grid(column=3, row=9)
    btn94 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn94))
    btn94.grid(column=4, row=9)
    btn95 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn95))
    btn95.grid(column=5, row=9)
    btn96 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn96))
    btn96.grid(column=6, row=9)
    btn97 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn97))
    btn97.grid(column=7, row=9)
    btn98 = Button(f2, text="y",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn98))
    btn98.grid(column=8, row=9)
    btn99 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn99))
    btn99.grid(column=9, row=9)
    btn910 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn910))
    btn910.grid(column=10, row=9)
    btn911 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn911))
    btn911.grid(column=11, row=9)
    btn912 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn912))
    btn912.grid(column=12, row=9)

    btn101 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn101))
    btn101.grid(column=1, row=10)
    btn102 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn102))
    btn102.grid(column=2, row=10)
    btn103 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn103))
    btn103.grid(column=3, row=10)
    btn104 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn104))
    btn104.grid(column=4, row=10)
    btn105 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn105))
    btn105.grid(column=5, row=10)
    btn106 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn106))
    btn106.grid(column=6, row=10)
    btn107 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn107))
    btn107.grid(column=7, row=10)
    btn108 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn108))
    btn108.grid(column=8, row=10)
    btn109 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn109))
    btn109.grid(column=9, row=10)
    btn1010 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1010))
    btn1010.grid(column=10, row=10)
    btn1011 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1011))
    btn1011.grid(column=11, row=10)
    btn1012 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1012))
    btn1012.grid(column=12, row=10)

    btn111 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn111))
    btn111.grid(column=1, row=11)
    btn112 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn112))
    btn112.grid(column=2, row=11)
    btn113 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn113))
    btn113.grid(column=3, row=11)
    btn114 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn114))
    btn114.grid(column=4, row=11)
    btn115 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn115))
    btn115.grid(column=5, row=11)
    btn116 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn116))
    btn116.grid(column=6, row=11)
    btn117 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn117))
    btn117.grid(column=7, row=11)
    btn118 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn118))
    btn118.grid(column=8, row=11)
    btn119 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn119))
    btn119.grid(column=9, row=11)
    btn1110 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1110))
    btn1110.grid(column=10, row=11)
    btn1111 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1111))
    btn1111.grid(column=11, row=11)
    btn1112 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1112))
    btn1112.grid(column=12, row=11)

    btn121 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn121))
    btn121.grid(column=1, row=12)
    btn122 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn122))
    btn122.grid(column=2, row=12)
    btn123 = Button(f2, text=random.choice(l_list),bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn123))
    btn123.grid(column=3, row=12)
    btn124 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn124))
    btn124.grid(column=4, row=12)
    btn125 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn125))
    btn125.grid(column=5, row=12)
    btn126 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn126))
    btn126.grid(column=6, row=12)
    btn127 = Button(f2, text="N",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn127))
    btn127.grid(column=7, row=12)
    btn128 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn128))
    btn128.grid(column=8, row=12)
    btn129 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn129))
    btn129.grid(column=9, row=12)
    btn1210 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(bnt1210))
    btn1210.grid(column=10, row=12)
    btn1211 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1211))
    btn1211.grid(column=11, row=12)
    btn1212 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1212))
    btn1212.grid(column=12, row=12)
def click(b):
    print("function called")
    global found
    global total
    global strg
    global count
    global l
    global score
    global w_found
    global l_found
    global c
    global conn
    if(b["text"]==""):
        found=1
        messagebox.showinfo("OOPS!!!!!!!!","wrong!!!! button")
        
    else:
        
        if(found==0):
            strg=strg+b["text"]
            strg=strg.lower()
            l_found=strg
            label2.configure(text="letters selected= "+l_found)
            print(strg)
            if(len(strg)>2):
                print('true')
                if(strg in word_list):
                    print('accesed')
                    found=1
                    if(strg in l):
                        found=0
                        return
                    w_found=w_found+"\n"+strg
                    score=score+len(strg)
                    c.execute("insert into scramble(temp1) values(?)",(score,))
                    total="score = "+str(score)
                    label.configure(text=total)
                    l.append(strg)
                    print(l)
                    label1.configure(text=w_found)
                elif(strg in word):
                    print('accesed')
                    found=1
                    if(strg in l):
                        found=0
                        return
                    w_found=w_found+"\n"+strg
                    score=score+len(strg)
                    c.execute("insert into scramble values(temp1) values(?)",(score,))
                    total="score = "+str(score)
                    label.configure(text=total)
                    l.append(strg)
                    print(l)
                    label1.configure(text=w_found)
    if(found==1):
        found=0
        strg=""
        l_found=strg
        label2.configure(text="letters selected= "+l_found)
    c.execute('select max(temp1) from scramble')
    k=c.fetchone()
    k=str(k)
    hscore.configure(text="highest Score = "+k)
    conn.commit()
c.execute('select max(temp1) from scramble')
k=c.fetchone()
k=str(k)
hscore.configure(text="Highest Score = "+k)
conn.commit()
btn11 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn11))
btn11.grid(column=1, row=1)
btn12 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn12))
btn12.grid(column=2, row=1)
btn13 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn13))
btn13.grid(column=3, row=1)
btn14 = Button(f2, text="D",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn14))
btn14.grid(column=4, row=1)
btn15 = Button(f2, text="W",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn15))
btn15.grid(column=5, row=1)
btn16 = Button(f2, text="X",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn16))
btn16.grid(column=6, row=1)
btn17 = Button(f2, text="K",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn17))
btn17.grid(column=7, row=1)
btn18 = Button(f2, text="L",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn18))
btn18.grid(column=8, row=1)
btn19 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn19))
btn19.grid(column=9, row=1)
btn110 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn110))
btn110.grid(column=10, row=1)
btn111a = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn111a))
btn111a.grid(column=11, row=1)
btn11298 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn11298))
btn11298.grid(column=12, row=1)

btn21 = Button(f2, text="X",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn21))
btn21.grid(column=1, row=2)
btn22 = Button(f2, text="E",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn22))
btn22.grid(column=2, row=2)
btn23 = Button(f2, text="I",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn23))
btn23.grid(column=3, row=2)
btn24 = Button(f2, text="J",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn24))
btn24.grid(column=4, row=2)
btn25 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn25))
btn25.grid(column=5, row=2)
btn26 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn26))
btn26.grid(column=6, row=2)
btn27 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn27))
btn27.grid(column=7, row=2)
btn28 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn28))
btn28.grid(column=8, row=2)
btn29 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn29))
btn29.grid(column=9, row=2)
btn210 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn210))
btn210.grid(column=10, row=2)
btn211 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn211))
btn211.grid(column=11, row=2)
btn212 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn212))
btn212.grid(column=12, row=2)

btn31 = Button(f2, text="M",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn31))
btn31.grid(column=1, row=3)
btn32 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn32))
btn32.grid(column=2, row=3)
btn33 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn33))
btn33.grid(column=3, row=3)
btn34 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn34))
btn34.grid(column=4, row=3)
btn35 = Button(f2, text="f",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn35))
btn35.grid(column=5, row=3)
btn36 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn36))
btn36.grid(column=6, row=3)
btn37 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn37))
btn37.grid(column=7, row=3)
btn38 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn38))
btn38.grid(column=8, row=3)
btn39 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn39))
btn39.grid(column=9, row=3)
btn310 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn310))
btn310.grid(column=10, row=3)
btn311 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn311))
btn311.grid(column=11, row=3)
btn312 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn312))
btn312.grid(column=12, row=3)

btn41 = Button(f2, text="O",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn41))
btn41.grid(column=1, row=4)
btn42 = Button(f2, text="U",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn42))
btn42.grid(column=2, row=4)
btn43 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn43))
btn43.grid(column=3, row=4)
btn44 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn44))
btn44.grid(column=4, row=4)
btn45 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn45))
btn45.grid(column=5, row=4)
btn46 = Button(f2, text="V",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn46))
btn46.grid(column=6, row=4)
btn47 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn47))
btn47.grid(column=7, row=4)
btn48 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn48))
btn48.grid(column=8, row=4)
btn49 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn49))
btn49.grid(column=9, row=4)
btn410 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn410))
btn410.grid(column=10, row=4)
btn411 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn411))
btn411.grid(column=11, row=4)
btn412 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn412))
btn412.grid(column=12, row=4)

btn51 = Button(f2, text="U",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn51))
btn51.grid(column=1, row=5)
btn52 = Button(f2, text="T",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn52))
btn52.grid(column=2, row=5)
btn53 = Button(f2, text="E",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn53))
btn53.grid(column=3, row=5)
btn54 = Button(f2, text="C",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn54))
btn54.grid(column=4, row=5)
btn55 = Button(f2, text="H",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn55))
btn55.grid(column=5, row=5)
btn56 = Button(f2, text="N",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn56))
btn56.grid(column=6, row=5)
btn57 = Button(f2, text="O",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn57))
btn57.grid(column=7, row=5)
btn58 = Button(f2, text="L",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn58))
btn58.grid(column=8, row=5)
btn59 = Button(f2, text="O",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn59))
btn59.grid(column=9, row=5)
btn510 = Button(f2, text="G",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn510))
btn510.grid(column=10, row=5)
btn511 = Button(f2, text="Y",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn511))
btn511.grid(column=11, row=5)
btn512 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn512))
btn512.grid(column=12, row=5)

btn61 = Button(f2, text="S",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn61))
btn61.grid(column=1, row=6)
btn62 = Button(f2, text="I",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn62))
btn62.grid(column=2, row=6)
btn63 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn63))
btn63.grid(column=3, row=6)
btn64 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn64))
btn64.grid(column=4, row=6)
btn65 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn65))
btn65.grid(column=5, row=6)
btn66 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn66))
btn66.grid(column=6, row=6)
btn67 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn67))
btn67.grid(column=7, row=6)
btn68 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn68))
btn68.grid(column=8, row=6)
btn69 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn69))
btn69.grid(column=9, row=6)
btn610 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn610))
btn610.grid(column=10, row=6)
btn611 = Button(f2, text="U",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn611))
btn611.grid(column=11, row=6)
btn612 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn612))
btn612.grid(column=12, row=6)

btn71 = Button(f2, text="E",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn71))
btn71.grid(column=1, row=7)
btn72 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn72))
btn72.grid(column=2, row=7)
btn73 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn73))
btn73.grid(column=3, row=7)
btn74 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn74))
btn74.grid(column=4, row=7)
btn75 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn75))
btn75.grid(column=5, row=7)
btn76 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn76))
btn76.grid(column=6, row=7)
btn77 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn77))
btn77.grid(column=7, row=7)
btn78 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn78))
btn78.grid(column=8, row=7)
btn79 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn79))
btn79.grid(column=9, row=7)
btn710 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn710))
btn710.grid(column=10, row=7)
btn711 = Button(f2, text="C",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn711))
btn711.grid(column=11, row=7)
btn712 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn712))
btn712.grid(column=12, row=7)

btn81 = Button(f2,text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn81))
btn81.grid(column=1, row=8)
btn82 = Button(f2, text="U",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn82))
btn82.grid(column=2, row=8)
btn83 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn83))
btn83.grid(column=3, row=8)
btn84 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn84))
btn84.grid(column=4, row=8)
btn85 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn85))
btn85.grid(column=5, row=8)
btn86 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn86))
btn86.grid(column=6, row=8)
btn87 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn87))
btn87.grid(column=7, row=8)
btn88 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn88))
btn88.grid(column=8, row=8)
btn89 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn89))
btn89.grid(column=9, row=8)
btn810 = Button(f2, text="V",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn810))
btn810.grid(column=10, row=8)
btn811 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn811))
btn811.grid(column=11, row=8)
btn812 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn812))
btn812.grid(column=12, row=8)

btn91 = Button(f2, text="K",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn91))
btn91.grid(column=1, row=9)
btn92 = Button(f2, text="L",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn92))
btn92.grid(column=2, row=9)
btn93 = Button(f2, text="I",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn93))
btn93.grid(column=3, row=9)
btn94 = Button(f2, text="B",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn94))
btn94.grid(column=4, row=9)
btn95 = Button(f2, text="R",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn95))
btn95.grid(column=5, row=9)
btn96 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn96))
btn96.grid(column=6, row=9)
btn97 = Button(f2, text="R",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn97))
btn97.grid(column=7, row=9)
btn98 = Button(f2, text="Y",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn98))
btn98.grid(column=8, row=9)
btn99 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn99))
btn99.grid(column=9, row=9)
btn910 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn910))
btn910.grid(column=10, row=9)
btn911 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn911))
btn911.grid(column=11, row=9)
btn912 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn912))
btn912.grid(column=12, row=9)

btn101 = Button(f2, text="J",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn101))
btn101.grid(column=1, row=10)
btn102 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn102))
btn102.grid(column=2, row=10)
btn103 = Button(f2, text="A",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn103))
btn103.grid(column=3, row=10)
btn104 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn104))
btn104.grid(column=4, row=10)
btn105 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn105))
btn105.grid(column=5, row=10)
btn106 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn106))
btn106.grid(column=6, row=10)
btn107 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn107))
btn107.grid(column=7, row=10)
btn108 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn108))
btn108.grid(column=8, row=10)
btn109 = Button(f2, text="B",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn109))
btn109.grid(column=9, row=10)
btn1010 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1010))
btn1010.grid(column=10, row=10)
btn1011 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1011))
btn1011.grid(column=11, row=10)
btn1012 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1012))
btn1012.grid(column=12, row=10)

btn111 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn111))
btn111.grid(column=1, row=11)
btn112 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn112))
btn112.grid(column=2, row=11)
btn113 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn113))
btn113.grid(column=3, row=11)
btn114 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn114))
btn114.grid(column=4, row=11)
btn115 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn115))
btn115.grid(column=5, row=11)
btn116 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn116))
btn116.grid(column=6, row=11)
btn117 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn117))
btn117.grid(column=7, row=11)
btn118 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn118))
btn118.grid(column=8, row=11)
btn119 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn119))
btn119.grid(column=9, row=11)
btn1110 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1110))
btn1110.grid(column=10, row=11)
btn1111 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1111))
btn1111.grid(column=11, row=11)
btn1112 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1112))
btn1112.grid(column=12, row=11)

btn121 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn121))
btn121.grid(column=1, row=12)
btn122 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn122))
btn122.grid(column=2, row=12)
btn123 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn123))
btn123.grid(column=3, row=12)
btn124 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn124))
btn124.grid(column=4, row=12)
btn125 = Button(f2, text="D",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn125))
btn125.grid(column=5, row=12)
btn126 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn126))
btn126.grid(column=6, row=12)
btn127 = Button(f2, text="N",bg="skyblue", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn127))
btn127.grid(column=7, row=12)
btn128 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn128))
btn128.grid(column=8, row=12)
btn129 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn129))
btn129.grid(column=9, row=12)
btn1210 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(bnt1210))
btn1210.grid(column=10, row=12)
btn1211 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1211))
btn1211.grid(column=11, row=12)
btn1212 = Button(f2, text="",bg="thistle4", fg="Black",width=3,height=1,font=('Helvetica','20'),command=lambda:click(btn1212))
btn1212.grid(column=12, row=12)

###################################################################################################################################
def tick(time1=''):   ##timer
    time2=time.strftime("%M:%S",)
    if(time2!=time1):
        time1=time2;
        timer.config(fg="red",bg="black",font=('Helvetica','10'),text="After 1 minute it will close automatically"+time2)
    timer.after(200,tick)
def quit_pro():
    messagebox.showinfo("OOPS!!!!!!!!","Times UP!!!! Your Score"+str(score))
    w.destroy()
timer=Label(w,text="you have 1 minute")
timer.grid(column=0,row=6)
tick()
w.after(60000,quit_pro)
w.mainloop()
